apiVersion: v1
kind: Service
metadata:
  name: yarp-proxy
  namespace: yarp
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ingress-yarp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingress-yarp
  name: yarp-proxy
  namespace: yarp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-yarp
  template:
    metadata:
      labels:
        app: ingress-yarp
    spec:
      containers:
      - name: yarp-proxy
        imagePullPolicy: IfNotPresent
        image: yarp/yarp
        ports:
        - containerPort: 8000
          name: proxy
          protocol: TCP
        - containerPort: 8443
          name: proxy-ssl
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: yarp-config
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8000
      volumes:
      - configMap:
          name: yarp-config
        name: yarp-config
---
